// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbF5fme1wN-z8Flui5Aani5xKefBP0hbw',
    appId: '1:878925598929:web:f3d737529965cc56c435f0',
    messagingSenderId: '878925598929',
    projectId: 'simm-a4fbf',
    authDomain: 'simm-a4fbf.firebaseapp.com',
    databaseURL: 'https://simm-a4fbf-default-rtdb.firebaseio.com',
    storageBucket: 'simm-a4fbf.firebasestorage.app',
    measurementId: 'G-YEXELCBS2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3VEC6l_g_n4jt0zgJFGC_EHKWSSfotSU',
    appId: '1:878925598929:android:4ca162e80283991dc435f0',
    messagingSenderId: '878925598929',
    projectId: 'simm-a4fbf',
    databaseURL: 'https://simm-a4fbf-default-rtdb.firebaseio.com',
    storageBucket: 'simm-a4fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEl26x8AYkLodUxT25sRqxdM0opZia9E',
    appId: '1:878925598929:ios:8d5410ee48824dd3c435f0',
    messagingSenderId: '878925598929',
    projectId: 'simm-a4fbf',
    databaseURL: 'https://simm-a4fbf-default-rtdb.firebaseio.com',
    storageBucket: 'simm-a4fbf.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEEl26x8AYkLodUxT25sRqxdM0opZia9E',
    appId: '1:878925598929:ios:8d5410ee48824dd3c435f0',
    messagingSenderId: '878925598929',
    projectId: 'simm-a4fbf',
    databaseURL: 'https://simm-a4fbf-default-rtdb.firebaseio.com',
    storageBucket: 'simm-a4fbf.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbF5fme1wN-z8Flui5Aani5xKefBP0hbw',
    appId: '1:878925598929:web:43e950a88bf2d37bc435f0',
    messagingSenderId: '878925598929',
    projectId: 'simm-a4fbf',
    authDomain: 'simm-a4fbf.firebaseapp.com',
    databaseURL: 'https://simm-a4fbf-default-rtdb.firebaseio.com',
    storageBucket: 'simm-a4fbf.firebasestorage.app',
    measurementId: 'G-9N9024JG2K',
  );
}
